### ISSUE TITLE
[Bug]: SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by librucha** [goreleaser/goreleaser-azure-devops-extension#709]
### What happened?

When I used this extension, got this error:

```
2023-12-05T22:03:56.4907974Z ##[section]Starting: goreleaser
2023-12-05T22:03:56.4911338Z ==============================================================================
2023-12-05T22:03:56.4911472Z Task         : GoReleaser
2023-12-05T22:03:56.4911529Z Description  : GoReleaser integration for Azure DevOps
2023-12-05T22:03:56.4911610Z Version      : 0.1.8
2023-12-05T22:03:56.4911663Z Author       : Engin Diri
2023-12-05T22:03:56.4911718Z Help         : https://goreleaser.com/intro/
2023-12-05T22:03:56.4911799Z ==============================================================================
2023-12-05T22:03:56.7120010Z ##[error]Unhandled: Unexpected identifier
2023-12-05T22:03:56.7138268Z ##[error]/agent/_work/_tasks/goreleaser_b4a32eee-3b3e-11ec-8d3d-0242ac130003/0.1.8/node_modules/axios/index.js:1
import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/agent/_work/_tasks/goreleaser_b4a32eee-3b3e-11ec-8d3d-0242ac130003/0.1.8/src/utils.js:19:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2023-12-05T22:03:56.7140708Z ##[section]Finishing: goreleaser
```

### How can we reproduce this?

```
trigger:
  branches:
    include:
      - refs/tags/*
  tags:
    include:
      - component_

pool: RixoUbuntuPool

name: $(SourceBranchName)_$(Date:yyyy-MM-dd)$(Rev:.r)

variables:
  GO_VERSION: "1.21.0"

stages:
  - stage: release
    jobs:
      - job: release
        steps:
          - checkout: self
          - task: GoTool@0
            inputs:
              version: "$(GO_VERSION)"
            displayName: Install Go
          - task: goreleaser@0
            inputs:
              version: 'latest'
              distribution: 'goreleaser-pro'
              args: ''
              workdir: '$(Build.SourcesDirectory)/component'
            env:
              GORELEASER_KEY: $(goreleaser-key)
```

### goreleaser-azure-devops-extension version

```bash
extension: 0.1.42
az devops service: Current agent version: '3.230.2'
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dirien** [comment]
is this still an error? @librucha

**Comment by librucha** [comment]
@dirien 
Yes i get the error right now.
![image](https://github.com/goreleaser/goreleaser-azure-devops-extension/assets/1335068/d908c6e1-b145-4f52-b3b9-0fce30df373b)

**Comment by dirien** [comment]
@librucha what version of the plugin are you using?

**Comment by librucha** [comment]
Task version is 0.1.8 and the problem happens during downloading "latest" version of goreleaser-pro

**Comment by librucha** [comment]
Extension version is 0.1.42
![image](https://github.com/goreleaser/goreleaser-azure-devops-extension/assets/1335068/71825e3d-1771-42a8-8658-e80a136fbe12)

**Comment by dirien** [comment]
@caarlos0 is there a change on the way we download the pro version? I do not have a key and can't test this.

**Comment by dirien** [comment]
@librucha what version of node are you using on your nodepool?

**Comment by dirien** [comment]
I updated the `axiom` lib and made a test for dev with a MS-hosted agent:
![image](https://github.com/goreleaser/goreleaser-azure-devops-extension/assets/38325136/648e67be-8a0a-489a-b038-db8b18ebb0b9)

**Comment by librucha** [comment]
@dirien We are using self hosted agents based on latest devops [images](https://github.com/actions/runner-images) agent version is 3.240.1 and node version is handled by the agent itself in task runtime.
Form agent built report vew have installed those [versions](https://github.com/actions/runner-images/blob/releases/ubuntu22/20240422/images/ubuntu/Ubuntu2204-Readme.md#nodejs):
```
#### Node.js
- 16.20.2
- 18.20.2
- 20.12.2
``` 
Your task is running on nodejs 10, MS is supporting node 16 in latest runtime. can it be a problem?

**Comment by librucha** [comment]
On release 0.1.44 still bug.
![image](https://github.com/goreleaser/goreleaser-azure-devops-extension/assets/1335068/d157a97e-5f7e-4a80-9902-1a5db06825db)

**Comment by librucha** [comment]
@dirien Maybe try to bump task version because can be cached elsewhere. During develop our extension i often recognized this behaviour.

**Comment by dirien** [comment]
@librucha give the latest version a try. I set the task version to `0.2.0`

![image](https://github.com/goreleaser/goreleaser-azure-devops-extension/assets/38325136/ecfb92d7-cba2-4753-bad0-784d1ea0148f)


and set the target to Node 16:

```json
  "execution": {
    "Node16": {
      "target": "src//index.js"
    }
  }
  ```

**Comment by librucha** [comment]
@dirien  I see in marketplace still version 0.1.44 (Latest) with task 0.1.8 I will wait for new version available.

**Comment by dirien** [comment]
@librucha now it should be available! Looking forward for your feedback

**Comment by librucha** [comment]
@dirien Great job. Is working well right now.
![image](https://github.com/goreleaser/goreleaser-azure-devops-extension/assets/1335068/9bf41ff9-0555-4546-862a-57a3401a93a1)
Thank you for support.
